name: Manual Deploy MkDocs

on:
  # 只有手动触发，不会自动触发
  workflow_dispatch:
    # 可以添加输入参数，让你在触发时提供额外信息（可选）
    inputs:
      deploy_message:
        description: '部署说明'
        required: false
        default: '手动触发的站点更新'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main  # 确保检出main分支的最新内容
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdocs gh-deploy --force
