name: Manual Deploy MkDocs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # 立即使用 Node 24，github官方服务器要升级版本不支持20了

jobs:
  deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Deploy
        run: mkdocs gh-deploy --force --clean
